### ISSUE TITLE
DataBase update

### ISSUE THREAD

**Issue by SoNiceElijah** [SoNiceElijah/UnnPortalBot#16]
# Планы по обновлению пакета для работы с БД

## Модуль

Хотелось бы поддержать следующий синтаксис

```js
const res =  
    await Users.select()
            .join(Requests)
            .where({ id : 10 })
            .orderBy([Users.c.id ])
            // Еще один вариант
            .orderBy(['id'])
            .skip(20)
            .limit(20)
            // В идеале, чтоб эту строчку можно было опустить
            .exec();
```

Не вошли выше, но достойны упоминания
```js
Users.select(['id', 'name', 'smth'])
    .sort()
    .distinct();
```

Что-то на сложном
```js
PGGLOB.select(['id', 'lol']).from(
    Users.select(['id', PGUTILS.count('lol')])
         .sort()
         .limit(20)
         .orderBy(['id'])
).where({ lol : { $lt : 20 }, id : 10 });
```

## Миграция

```yaml
# db.config

latest : 3.0.0

v0.0.0 :
    - requests.sql
    - user.sql
v0.0.1 :
    - user_up_1.sql
v0.2.1 : ...
v1.0.5 : ...
v2.0.0 :
    - super_new_base.sql
v2.3.1 :
    - file.sql
v3.0.0 :
    - file.sql
```

```yaml
dbverison : 2.0.0
```

Database.js
```js
await pgConnecter.connect(config.pgconnection);
await pgConnecter.freshdb(config.dbverison);
```
